apps/contas/urls.py
from django.conf.urls import url
from apps.contas import views
from django.urls import path, reverse_lazy
# Utilizado para envio de emails de recuperação de password
from django.contrib.auth import views as auth_views

app_name = 'contas'

urlpatterns = [
    path("login/", views.login_view, name="login"),
    path("logout/", views.logout_view, name="logout"),
    path("register/", views.register, name="register"),
    path("terms/", views.terms, name="terms"),

    # update user profile
    path("change_password/", views.change_password, name="change_password"),
    path("perfil/<user_slug>/alterar", views.user_profile_change, name="user_profile_change"),
    path("perfil/<user_slug>/alterar_foto", views.user_profile_foto_change, name="user_profile_foto_change"),

    # reset password
    path('reset_password/', auth_views.PasswordResetView.as_view(
        template_name="contas/reset_password.html",
        email_template_name='contas/password_reset_email.html',
        subject_template_name='contas/password_reset_subject.txt',
        success_url=reverse_lazy('contas:password_reset_done')
    ), name="password_reset"),
    path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(
        template_name="contas/reset_password_sent.html"
    ), name="password_reset_done"),
    path('reset/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(
        template_name="contas/recover_password.html",
        success_url=reverse_lazy('contas:password_reset_complete')
    ), name="password_reset_confirm"),
    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(
        template_name="contas/reset_password_complete.html"
    ), name="password_reset_complete"),
]

# correção namespace reset passord
# https://coderoad.ru/52293502/NoReverseMatch-%D0%BD%D0%B0-accounts-password_reset
# https://simpleisbetterthancomplex.com/tutorial/2016/09/19/how-to-create-password-reset-view.html


# Documentação consultada:
# https://docs.djangoproject.com/en/2.2/topics/auth/default/

apps/gestao_escolar/urls.py
from apps.gestao_escolar import views
from django.urls import path

app_name = 'gestao_escolar'

urlpatterns = [

    path("", views.homepage, name="homepage_blank"),
    path("ano-letivo/lista/", views.school_year_list, name="school_year_list"),
    path("ano-letivo/criar/", views.school_year_add, name="school_year_add"),
    path("ano-letivo/<ano_letivo_slug>/alterar", views.school_year_change, name="school_year_change"),
    path("ano-letivo/<ano_letivo_slug>/remover", views.school_year_delete, name="school_year_delete"),

    path("ano-letivo/", views.homepage, name="school_year"),

    path("ano-letivo/<ano_letivo_slug>/turma/lista", views.homepage, name="school_class_list"),

    path("ano-letivo/<ano_letivo_slug>/turma/criar", views.school_class_add, name="school_class_add"),
    path("ano-letivo/<ano_letivo_slug>/turma/<turma_slug>", views.school_class_detail, name="school_class_detail"),
    path("ano-letivo/<ano_letivo_slug>/turma/<turma_slug>/alterar", views.school_class_change,
         name="school_class_change"),
    path("ano-letivo/<ano_letivo_slug>/turma/<turma_slug>/remover", views.school_class_delete,
         name="school_class_delete"),
    path("ano-letivo/<ano_letivo_slug>/turma/<turma_slug>/aluno/criar", views.student_add,
         name="student_add"),
    path("ano-letivo/<ano_letivo_slug>/turma/<turma_slug>/aluno/criar_alunos", views.student_add_multiple,
         name="student_add_multiple"),

    path("ano-letivo/<ano_letivo_slug>/turma/<turma_slug>/aluno/<aluno_slug>", views.student_detail,
         name="student_detail"),
    path("ano-letivo/<ano_letivo_slug>/turma/<turma_slug>/aluno/<aluno_slug>/alterar", views.student_change,
         name="student_change"),
    path("ano-letivo/<ano_letivo_slug>/turma/<turma_slug>/aluno/<aluno_slug>/alterar_foto", views.student_foto_change,
         name="student_foto_change"),
    path("ano-letivo/<ano_letivo_slug>/turma/<turma_slug>/aluno/<aluno_slug>/remover", views.student_delete,
         name="student_delete"),

    path("escola/lista", views.school_list, name="school_list"),
    path("escola/criar", views.school_add, name="school_add"),
    path("escola/<escola_slug>/alterar", views.school_change, name="school_change"),
    path("escola/<escola_slug>/remover", views.school_delete, name="school_delete"),
]

apps/landing_page/urls.py
from django.urls import path

from apps.landing_page.views import landing_page

app_name = 'landing_page'

urlpatterns = [
    path('', landing_page, name='landing_page'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.landing_page.urls')),
    path('contas/', include('apps.contas.urls')),
    path('gestao_escolar/', include('apps.gestao_escolar.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/contas/models.py
from django.core.validators import RegexValidator, re
from django.db import models
from django.core import validators
from django.template.defaultfilters import slugify
from django_resized import ResizedImageField

from django.contrib.auth.models import (
    AbstractBaseUser, UserManager, PermissionsMixin
)


# Documentação consultada
# https://docs.djangoproject.com/en/2.2/ref/contrib/auth/

# código fonte 'class User'
# https://github.com/django/django/blob/main/django/contrib/auth/models.py

class User(AbstractBaseUser, PermissionsMixin):
    """Modelo base para os utilizadores"""

    username = models.CharField(
        'Username', max_length=30, unique=True, validators=[
            validators.RegexValidator(
                re.compile('^[\w.@+-]+$'),
                'Indique um username válido. '
                'Este campo deve conter apenas letras, números '
                'e os carateres: @/./+/-/_.',
                'inválido'
            )
        ], help_text='Um nome curto para identificá-lo de forma única no site'
    )
    email = models.EmailField('Email', max_length=254, unique=True)
    slug = models.SlugField('caminho', max_length=255, null=False, unique=True)

    first_name = models.CharField('Nome', max_length=100, blank=True)
    last_name = models.CharField('Apelido', max_length=100, blank=True)
    address = models.CharField('Morada', max_length=250, blank=True)

    # error message when a wrong format entered
    phone_message = 'Introduza um número com 9 dígitos.'
    # regex for phone validation
    phone_regex = RegexValidator(
        regex=r'^\d{9}$',
        message=phone_message
    )
    phone = models.CharField(
        'Telefone',
        validators=[phone_regex],
        max_length=60,
        null=True,
        blank=True
    )

    # avatar = models.ImageField(
    #     'Foto', upload_to='media/fotos_profs/',
    #     default='media/fotos_profs/no-img.jpg'
    # )

    avatar = ResizedImageField(
        size=[185, 185],
        upload_to='fotos_users/',
        default='fotos_users/no_image.png',
        crop=['middle', 'center'],
        quality=75
    )

    is_active = models.BooleanField('Ativo', default=True)
    is_staff = models.BooleanField('Administrador', default=False)
    created = models.DateTimeField('Criado em', auto_now_add=True)
    modified = models.DateTimeField('Modificado em', auto_now=True)

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['email']

    objects = UserManager()

    class Meta:
        verbose_name = 'Utilizador'
        verbose_name_plural = 'Utilizadores'
        ordering = ['first_name']

    def __str__(self):
        return self.first_name or self.username

    def get_full_name(self):
        """ Retorna o o primeiro nome mais o segundo nome com um espaço no meio.
        função strip() retira espaços no início e no fim da string."""
        full_name = '%s %s' % (self.first_name, self.last_name)
        return full_name.strip()

    get_full_name.short_description = 'Nome'

    def get_short_name(self):
        return self.first_name

    def save(self, *args, **kwargs):
        super(User, self).save(*args, **kwargs)
        if not self.slug:
            self.slug = slugify(self.username)
            self.save()

# atualizar o campo número de telefone... verificar se isto funciona
# https://stackoverflow.com/questions/59480134/how-to-store-a-phone-number-in-django-model


# referências consultadas

# exemplos de user.model
# https://simpleisbetterthancomplex.com/tutorial/2016/07/22/how-to-extend-django-user-model.html#abstractuser

# documentação
# https://docs.djangoproject.com/en/2.2/ref/contrib/auth/

# código fonte 'class User'
# https://github.com/django/django/blob/main/django/contrib/auth/models.py


# *** Consulted documentation ****
# Writing and running tests:
# https://docs.djangoproject.com/en/2.2/topics/testing/overview/

# Class RequestFactory:
# https://docs.djangoproject.com/en/2.2/topics/testing/advanced/

# Customizing authentication in Django:
# https://docs.djangoproject.com/en/2.2/topics/auth/customizing/

apps/contas/forms.py
from django.contrib.auth.forms import UserCreationForm
from django import forms
from .models import User


class UserAdminCreationForm(UserCreationForm):
    """ formulário de criação de utilizador """

    class Meta:
        model = User
        fields = ['username', 'email']


class UserAdminForm(forms.ModelForm):
    """ formulário de configuração de mais dados do utilizador no 'Admin' """

    class Meta:
        model = User
        fields = [
            'username', 'email', 'first_name', 'last_name', 'address', 'phone',
            'is_active', 'is_staff', 'avatar', 'slug',
        ]


class UserChangeForm(forms.ModelForm):
    """ formulário para configuração de dados do utilizador"""

    class Meta:
        model = User
        fields = [
            'first_name', 'last_name', 'address', 'phone',
        ]


class UserFotoChangeForm(forms.ModelForm):
    """ formulário para atualização de foto do utilizador"""

    class Meta:
        model = User
        fields = ['avatar', ]

apps/contas/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm
from django.contrib.auth import authenticate, login, logout, update_session_auth_hash
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from .forms import UserAdminCreationForm, UserFotoChangeForm, UserChangeForm
from .models import User
from apps.gestao_escolar.views import side_bar_func


def register(request):
    if request.method == "POST":
        form = UserAdminCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, f"Nova conta criada com sucesso: '{username}''")
            login(request, user, 'apps.contas.backends.EmailBackend')
            messages.success(request, f"Efetuou login com sucesso como '{username}'")
            return redirect("gestao_escolar:school_year")
        else:
            if form.error_messages:
                messages.error(request, "Falha no registo! Verifique os campos do formulário.")
            template_name = "contas/register.html"
            context = {"form": form}
            return render(request, template_name, context)

    form = UserAdminCreationForm
    return render(request=request, template_name="contas/register.html", context={"form": form})


def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(request=request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                messages.success(request, f"Efetuou login com sucesso como '{username}'")
                return redirect('gestao_escolar:school_year')
            else:
                messages.error(request, "Utilizador e/ou password inválidos.")
        else:
            messages.error(request, "Utilizador e/ou password inválidos.")
    form = AuthenticationForm()
    template_name = "contas/login.html"
    context = {"form": form}
    return render(request, template_name, context)


def logout_view(request):
    logout(request)
    messages.success(request, "Efetuou logout com sucesso!")
    return redirect("landing_page:landing_page")


def terms(request):
    template_name = 'contas/terms.html'
    return render(request, template_name)


@login_required
def user_profile_change(request, user_slug):
    """
        Apresenta os dados do utilizador e permite que este os altere.
        # link -> navbar -> icon configurações -> "alterar dados"
        path("perfil/<user_slug>/alterar", views.user_profile_change,
         name="user_profile_change"),
    """
    user = User.objects.get(slug=user_slug)

    form = UserChangeForm(instance=user)

    if request.method == 'POST':
        form = UserChangeForm(request.POST, instance=user)
        if form.is_valid():
            form.save()
            return redirect('gestao_escolar:homepage_blank')

    template_name = 'contas/user_profile_change.html'
    context = {
        'form': form,
    }

    context = side_bar_func(request, context)

    return render(request, template_name, context)


@login_required
def user_profile_foto_change(request, user_slug):
    """
        Apresenta a foto do utilizador e permite que este a altere.
        # link -> navbar -> icon configurações -> "alterar foto"
        # path("perfil/<user_slug>/alterar_foto", views.user_profile_foto_change, name="user_profile_foto_change"),
    """

    user = User.objects.get(slug=user_slug)

    form = UserFotoChangeForm(instance=user)

    if request.method == 'POST':
        form = UserFotoChangeForm(request.POST, request.FILES, instance=user)
        if form.is_valid():
            form.save()
            return redirect('gestao_escolar:homepage_blank')

    template_name = 'contas/user_profile_foto_change.html'
    context = {
            'form': form,
        }

    context = side_bar_func(request, context)

    return render(request, template_name, context)


@login_required
def change_password(request):
    """
        Apresenta a formulário para alteração de password do utilizador.
        # link -> navbar -> icon configurações -> "alterar password"
        path("change_password/", views.change_password, name="change_password"),
    """
    # colocar este url
    # path("change_password/", views.change_password, name="change_password"),

    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)  # Importante!
            messages.success(request, 'A sua password foi atualizada com sucesso!')
            return redirect('contas:change_password')
        else:
            messages.error(request, "Corrija os erros abaixo indicados!")
    else:
        form = PasswordChangeForm(request.user)
    return render(request, 'contas/change_password.html', {
        'form': form
    })

templates/contas/login.html
{% load static %}
{% load widget_tweaks %}

<!DOCTYPE html>
<html lang="pt-PT">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>r+Prof | Login</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="{% static 'AdminLTE/plugins/fontawesome-free/css/all.min.css' %}">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <!-- icheck bootstrap -->
    <link rel="stylesheet" href="{% static 'AdminLTE/plugins/icheck-bootstrap/icheck-bootstrap.min.css' %}">
    <!-- Theme style -->
    <link rel="stylesheet" href="{% static 'AdminLTE/css/adminlte.min.css' %}">
    <!-- Google Font: Source Sans Pro -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">

    <!-- r+Prof style -->
    <link rel="stylesheet" href="{% static 'r+prof/css/r+prof.css' %}">

    <!-- Botões de alerta -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>

    <!-- ToastsR -->
    <script src="http://code.jquery.com/jquery-1.9.1.min.js"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'AdminLTE/plugins/toastr/toastr.css' %}" media="all">
    <script type="text/javascript" src="{% static 'AdminLTE/plugins/toastr/toastr.min.js' %}"></script>
</head>

<body class="hold-transition login-page">

<!-- Mensagens do Django -->
{% if messages %}
    {% for message in messages %}
        {% if message.tags == 'success' %}
            <script type=text/javascript>toastr.{{ message.tags }}('{{ message }}')</script>
        {% elif message.tags == 'info' %}
            <script type=text/javascript>toastr.{{ message.tags }}('{{ message }}')</script>
        {% elif message.tags == 'warning' %}
            <script type=text/javascript>toastr.{{ message.tags }}('{{ message }}')</script>
        {% elif message.tags == 'error' %}
            <script type=text/javascript>toastr.{{ message.tags }}('{{ message }}')</script>
        {% endif %}
    {% endfor %}
{% endif %}

<div class="login-box">
    <div class="login-logo">
        <a href="{% url 'landing_page:landing_page' %}"><b>r+Prof</b></a>
    </div>
    <!-- /.login-logo -->
    <div class="card">
        <div class="card-body login-card-body">

            <p class="login-box-msg">Efetue o login para iniciar a sua sessão</p>

            <form method="post">
                {% csrf_token %}
                <div class="input-group mb-3">
                    {% render_field form.username class="form-control" placeholder="Email ou Username" %}
                    <div class="input-group-append">
                        <div class="input-group-text">
                            <span class="fas fa-user"></span>
                        </div>
                    </div>
                </div>

                <div class="input-group mb-3">
                    {% render_field form.password class="form-control" placeholder="Password" %}
                    <div class="input-group-append">
                        <div class="input-group-text">
                            <span class="fas fa-lock"></span>
                        </div>
                    </div>
                </div>

                <div class="row justify-content-center">
                    <div class="col-4">
                        <button type="submit" class="btn btn-primary btn-block">Login</button>
                    </div>
                    <!-- /.col -->
                </div>
            </form>

            <div class="social-auth-links text-center mb-3">
                <p>- OU -</p>
            </div>

            <p class="mb-1">
                <a href="{% url 'contas:password_reset' %}">Recupere a password</a>
            </p>
            <p class="mb-0">
                <a href="{% url 'contas:register' %}" class="text-center">Registar como novo utilizador</a>
            </p>
        </div>
        <!-- /.login-card-body -->
    </div>
</div>
<!-- /.login-box -->

<!-- jQuery -->
<script src="{% static 'AdminLTE/plugins/jquery/jquery.min.js' %}"></script>
<!-- Bootstrap 4 -->
<script src="{% static 'AdminLTE/plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<!-- AdminLTE App -->
<script src="{% static 'AdminLTE/js/adminlte.min.js' %}"></script>

</body>
</html>

templates/contas/password_reset_email.html
{% autoescape off %}
Senhor {{ user.get_username }}, para definir uma nova palavra-passe é simples.

Basta clicar neste no seguinte link:

{{ protocol }}://{{ domain }}{% url 'contas:password_reset_confirm' uidb64=uid token=token %}

Obrigado pela preferência,

A Equipa r+Prof
{% endautoescape %}

templates/contas/register.html
{% load static %}
{% load widget_tweaks %}

<!DOCTYPE html>
<html lang="pt-PT">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>r+Prof | Register</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Font Awesome -->
    <link rel="stylesheet" href="{% static 'AdminLTE/plugins/fontawesome-free/css/all.min.css' %}">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <!-- icheck bootstrap -->
    <link rel="stylesheet" href="{% static 'AdminLTE/plugins/icheck-bootstrap/icheck-bootstrap.min.css' %}">
    <!-- Theme style -->
    <link rel="stylesheet" href="{% static 'AdminLTE/css/adminlte.min.css' %}">
    <!-- Google Font: Source Sans Pro -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">

    <!-- r+Prof style -->
    <link rel="stylesheet" href="{% static 'r+prof/css/r+prof.css' %}">

    <!-- botões alerta -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>


    <!-- ToastsR  -->
    <script src="http://code.jquery.com/jquery-1.9.1.min.js"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'AdminLTE/plugins/toastr/toastr.css' %}" media="all">
    <script type="text/javascript" src="{% static 'AdminLTE/plugins/toastr/toastr.min.js' %}"></script>


</head>
<body class="hold-transition register-page">

<!-- Mensagens do Django -->
{% if messages %}
    {% for message in messages %}
        {% if message.tags == 'success' %}
            <script type=text/javascript>toastr.{{ message.tags }}('{{ message }}')</script>
        {% elif message.tags == 'info' %}
            <script type=text/javascript>toastr.{{ message.tags }}('{{ message }}')</script>
        {% elif message.tags == 'warning' %}
            <script type=text/javascript>toastr.{{ message.tags }}('{{ message }}')</script>
        {% elif message.tags == 'error' %}
            <script type=text/javascript>toastr.{{ message.tags }}('{{ message }}')</script>
        {% endif %}
    {% endfor %}
{% endif %}

<div class="register-box">
    <div class="register-logo">
        <a href="{% url 'landing_page:landing_page' %}"><b>r+Prof</b></a>
    </div>
    <div class="card">
        <div class="card-body register-card-body">
            <p class="login-box-msg">Efetue o seu registo no r+Prof</p>

            <form method="post">
                {% csrf_token %}
                {% for field in form %}

                    {% if field.name == "username" %}
                        <div class="input-group mb-3">
                            {% render_field field class="form-control" placeholder=field.label %}
                            <div class="input-group-append">
                                <div class="input-group-text">
                                    <span class="fas fa-user"></span>
                                </div>
                            </div>
                        </div>
                    {% endif %}

                    {% if field.name == "email" %}
                        <div class="input-group mb-3">
                            {% render_field field class="form-control" placeholder=field.label %}
                            <div class="input-group-append">
                                <div class="input-group-text">
                                    <span class="fas fa-envelope"></span>
                                </div>
                            </div>
                        </div>
                    {% endif %}

                    {% if field.name == "password1" %}
                        <div class="input-group mb-3">
                            {% render_field field class="form-control" placeholder=field.label %}
                            <div class="input-group-append">
                                <div class="input-group-text">
                                    <span class="fas fa-lock"></span>
                                </div>
                            </div>
                        </div>
                    {% endif %}

                    {% if field.name == "password2" %}
                        <div class="input-group mb-3">
                            {% render_field field class="form-control" placeholder=field.label %}
                            <div class="input-group-append">
                                <div class="input-group-text">
                                    <span class="fas fa-lock"></span>
                                </div>
                            </div>
                        </div>
                    {% endif %}

                    {% for error in field.errors %}
                        <ul>
                            <li class="text-danger" style="list-style-type:square;">
                                {{ error }}
                            </li>
                        </ul>
                    {% endfor %}

                {% endfor %}

                <div class="row">
                    <div class="col-8">
                        <div class="icheck-primary">
                            <input type="checkbox" id="agreeTerms" name="terms" value="agree" required>
                            <label for="agreeTerms">
                                Concordo com os
                                <a href="{% url 'contas:terms' %}" target="popup"
                                   onclick="window.open(
                                       '{% url 'contas:terms' %}',
                                           'popup',
                                           'top=300,left=500,width=600,height=400'
                                           );
                                   return false;">
                                    termos
                                </a>
                                de utilização do site
                            </label>
                        </div>
                    </div>
                    <!-- /.col -->
                    <div class="col-4">
                        <button type="submit" class="btn btn-primary btn-block">Registar</button>
                    </div>
                    <!-- /.col -->
                </div>
            </form>

            <div class="social-auth-links text-center mb-3">
                <p>- OU -</p>
            </div>

            <a href="{% url 'contas:login' %}" class="text-center">Já estou registado... efetuar o login</a>
        </div>
        <!-- /.form-box -->
    </div><!-- /.card -->
</div>
<!-- /.register-box -->

<!-- jQuery -->
<script src="{% static 'AdminLTE/plugins/jquery/jquery.min.js' %}"></script>
<!-- Bootstrap 4 -->
<script src="{% static 'AdminLTE/plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<!-- AdminLTE App -->
<script src="{% static 'AdminLTE/js/adminlte.min.js' %}"></script>
</body>
</html>

templates/contas/reset_password.html
{% load static %}
{% load widget_tweaks %}

<!DOCTYPE html>
<html lang="pt-PT">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>r+Prof | Forgot Password</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Font Awesome -->
    <link rel="stylesheet" href="{% static 'adminLTE/plugins/fontawesome-free/css/all.min.css' %}">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <!-- icheck bootstrap -->
    <link rel="stylesheet" href="{% static 'adminLTE/plugins/icheck-bootstrap/icheck-bootstrap.min.css' %}">
    <!-- Theme style -->
    <link rel="stylesheet" href="{% static 'adminLTE/css/adminlte.min.css' %}">
    <!-- Google Font: Source Sans Pro -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">

    <!-- r+Prof style -->
    <link rel="stylesheet" href="{% static 'r+prof/css/r+prof.css' %}">

</head>
<body class="hold-transition login-page">
<div class="login-box">
    <div class="login-logo">
        <a href="{% url 'landing_page:landing_page' %}"><b>r+Prof</b></a>
    </div>
    <!-- /.login-logo -->
    <div class="card">
        <div class="card-body login-card-body">
            <p class="login-box-msg">
                Esqueceu-se da password?<br>Recupere uma nova senha.
            </p>

            <form method="post">
                {% csrf_token %}
                {% for field in form %}

                    {% if field.name == "email" %}
                        <div class="input-group mb-3">
                            {% render_field field class="form-control" placeholder=field.label %}
                            <div class="input-group-append">
                                <div class="input-group-text">
                                    <span class="fas fa-envelope"></span>
                                </div>
                            </div>
                        </div>
                    {% endif %}
                {% endfor %}

                <div class="row justify-content-center">
                    <div class="col-8">
                        <button type="submit" class="btn btn-primary btn-block">Solicitar nova password</button>
                    </div>
                    <!-- /.col -->
                </div>
            </form>

            <p class="mt-3 mb-1">
                <a href="{% url 'contas:login' %}">Login</a>
            </p>
            <p class="mb-0">
                <a href="{% url 'contas:register' %}" class="text-center">Registar como novo utilizador</a>
            </p>
        </div>
        <!-- /.login-card-body -->
    </div>
</div>
<!-- /.login-box -->

<!-- jQuery -->
<script src="{% static 'adminLTE/plugins/jquery/jquery.min.js' %}"></script>
<!-- Bootstrap 4 -->
<script src="{% static 'adminLTE/plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<!-- adminLTE App -->
<script src="{% static 'adminLTE/js/adminlte.min.js' %}"></script>


</body>
</html>