apps/contas/urls.py
from django.conf.urls import url
from apps.contas import views
from django.urls import path, reverse_lazy
# Utilizado para envio de emails de recuperação de password
from django.contrib.auth import views as auth_views

app_name = 'contas'

urlpatterns = [
    path("login/", views.login_view, name="login"),
    path("logout/", views.logout_view, name="logout"),
    path("register/", views.register, name="register"),
    path("terms/", views.terms, name="terms"),

    # update user profile
    path("change_password/", views.change_password, name="change_password"),
    path("perfil/<user_slug>/alterar", views.user_profile_change, name="user_profile_change"),
    path("perfil/<user_slug>/alterar_foto", views.user_profile_foto_change, name="user_profile_foto_change"),

    # reset password
    path('reset_password/', auth_views.PasswordResetView.as_view(
        template_name="contas/reset_password.html",
        email_template_name='contas/password_reset_email.html',
        subject_template_name='contas/password_reset_subject.txt',
        success_url=reverse_lazy('contas:password_reset_done')
    ), name="password_reset"),
    path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(
        template_name="contas/reset_password_sent.html"
    ), name="password_reset_done"),
    path('reset/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(
        template_name="contas/recover_password.html",
        success_url=reverse_lazy('contas:password_reset_complete')
    ), name="password_reset_confirm"),
    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(
        template_name="contas/reset_password_complete.html"
    ), name="password_reset_complete"),
]

# correção namespace reset passord
# https://coderoad.ru/52293502/NoReverseMatch-%D0%BD%D0%B0-accounts-password_reset
# https://simpleisbetterthancomplex.com/tutorial/2016/09/19/how-to-create-password-reset-view.html


# Documentação consultada:
# https://docs.djangoproject.com/en/2.2/topics/auth/default/

apps/gestao_escolar/urls.py
from apps.gestao_escolar import views
from django.urls import path

app_name = 'gestao_escolar'

urlpatterns = [

    path("", views.homepage, name="homepage_blank"),
    path("ano-letivo/lista/", views.school_year_list, name="school_year_list"),
    path("ano-letivo/criar/", views.school_year_add, name="school_year_add"),
    path("ano-letivo/<ano_letivo_slug>/alterar", views.school_year_change, name="school_year_change"),
    path("ano-letivo/<ano_letivo_slug>/remover", views.school_year_delete, name="school_year_delete"),

    path("ano-letivo/", views.homepage, name="school_year"),

    path("ano-letivo/<ano_letivo_slug>/turma/lista", views.homepage, name="school_class_list"),

    path("ano-letivo/<ano_letivo_slug>/turma/criar", views.school_class_add, name="school_class_add"),
    path("ano-letivo/<ano_letivo_slug>/turma/<turma_slug>", views.school_class_detail, name="school_class_detail"),
    path("ano-letivo/<ano_letivo_slug>/turma/<turma_slug>/alterar", views.school_class_change,
         name="school_class_change"),
    path("ano-letivo/<ano_letivo_slug>/turma/<turma_slug>/remover", views.school_class_delete,
         name="school_class_delete"),
    path("ano-letivo/<ano_letivo_slug>/turma/<turma_slug>/aluno/criar", views.student_add,
         name="student_add"),
    path("ano-letivo/<ano_letivo_slug>/turma/<turma_slug>/aluno/criar_alunos", views.student_add_multiple,
         name="student_add_multiple"),

    path("ano-letivo/<ano_letivo_slug>/turma/<turma_slug>/aluno/<aluno_slug>", views.student_detail,
         name="student_detail"),
    path("ano-letivo/<ano_letivo_slug>/turma/<turma_slug>/aluno/<aluno_slug>/alterar", views.student_change,
         name="student_change"),
    path("ano-letivo/<ano_letivo_slug>/turma/<turma_slug>/aluno/<aluno_slug>/alterar_foto", views.student_foto_change,
         name="student_foto_change"),
    path("ano-letivo/<ano_letivo_slug>/turma/<turma_slug>/aluno/<aluno_slug>/remover", views.student_delete,
         name="student_delete"),

    path("escola/lista", views.school_list, name="school_list"),
    path("escola/criar", views.school_add, name="school_add"),
    path("escola/<escola_slug>/alterar", views.school_change, name="school_change"),
    path("escola/<escola_slug>/remover", views.school_delete, name="school_delete"),
]

apps/landing_page/urls.py
from django.urls import path

from apps.landing_page.views import landing_page

app_name = 'landing_page'

urlpatterns = [
    path('', landing_page, name='landing_page'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.landing_page.urls')),
    path('contas/', include('apps.contas.urls')),
    path('gestao_escolar/', include('apps.gestao_escolar.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}

<!DOCTYPE html>
<!--
This is a starter template page. Use this page to start your new project from
scratch. This page gets rid of all links and provides the needed markup only.
-->
<!-- pt-PT - português de Portugal. -->
<html lang="pt-PT">
<head>
    <!-- character encoding for the HTML document - UTF-8 character set, covers almost all of the characters and symbols -->
    <!-- in the world! -->
    <meta charset="utf-8">
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The X-UA-Compatible meta tag allows to choose what version of Internet Explorer the page should be rendered as -->
    <!-- edge mode tells Internet Explorer to display content in the highest mode available -->
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <!-- title tab -->
    <title>r+Prof</title>
    <!-- Font Awesome Icons -->
    <link rel="stylesheet" href="{% static 'adminLTE/plugins/fontawesome-free/css/all.min.css' %}">
    <!-- Theme style -->
    <link rel="stylesheet" href="{% static 'adminLTE/css/adminlte.min.css' %}">
    <!-- Google Font: Source Sans Pro -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">

    <!-- r+Prof style -->
    <link rel="stylesheet" href="{% static 'r+prof/css/r+prof.css' %}">

    <!-- r+Prof favicon -->
    <link rel="icon" type="image/svg+xml" href="{% static 'r+prof/img/favicon_io/rProf_favicon.svg ' %}">
    <link rel="icon" type="image/png" href="{% static 'r+prof/img/favicon_io/rProf_favicon.png ' %}">

    <!-- ToastsR -->
    <script src="http://code.jquery.com/jquery-1.9.1.min.js"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'AdminLTE/plugins/toastr/toastr.css' %}" media="all">
    <script type="text/javascript" src="{% static 'AdminLTE/plugins/toastr/toastr.min.js' %}"></script>

</head>
<body class="hold-transition sidebar-mini layout-fixed layout-navbar-fixed">

<!-- Mensagens do Django -->
{% if messages %}
    {% for message in messages %}
        {% if message.tags == 'success' %}
            <script type=text/javascript>toastr.{{ message.tags }}('{{ message }}')</script>
        {% elif message.tags == 'info' %}
            <script type=text/javascript>toastr.{{ message.tags }}('{{ message }}')</script>
        {% elif message.tags == 'warning' %}
            <script type=text/javascript>toastr.{{ message.tags }}('{{ message }}')</script>
        {% elif message.tags == 'error' %}
            <script type=text/javascript>toastr.{{ message.tags }}('{{ message }}')</script>
        {% endif %}
    {% endfor %}
{% endif %}

<div class="wrapper">

    <!-- Navbar -->
    <nav class="main-header navbar navbar-expand navbar-white navbar-light">
        <!-- Left navbar links -->
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
            </li>
            <li class="nav-item d-none d-sm-inline-block">
                <span class="oi oi-home"></span>
                <a href="{% url 'gestao_escolar:school_year' %}" class="nav-link"><i class="fas fa-home"></i></a>
            </li>
            </li>
        </ul>
        <!-- Right navbar links -->
        <ul class="navbar-nav ml-auto">
            <!-- Contact -->
            <li class="nav-item d-none d-sm-inline-block">

                <a href="mailto:apprprof@gmail.com" class="nav-link"> <i class="far fa-envelope"></i>&nbsp
                    apprprof@gmail.com</a>
            </li>
            <!-- Settings dropdown -->
            <li class="nav-item dropdown show ">
                <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" aria-expanded="true">
                    <i class="fas fa-cog"></i>
                </a>
                <div class="dropdown-menu hide" x-placement="bottom-start"
                     style="position: absolute; will-change: transform; top: 0px; left: 0px; transform: translate3d(-5px, 40px, 0px);">
                    <a class="dropdown-item" tabindex="-1" href="{% url 'contas:user_profile_change' user.slug %}">Editar conta</a>
                    <a class="dropdown-item" tabindex="-1" href="{% url 'contas:user_profile_foto_change' user.slug %}">Alterar foto</a>
                    <a class="dropdown-item" tabindex="-1" href="{% url 'contas:change_password' %}">Alterar Password</a>
                </div>
            </li>

            <!-- End Settings dropdown -->
        </ul>
    </nav>
    <!-- /.navbar -->

    {% block sidebar %}

        {% include 'sidebar.html' %}

    {% endblock %}


    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        {% block content %}

        {% endblock %}
    </div>
    <!-- /.content-wrapper -->

    {% block footer %}

        {% include 'footer.html' %}

    {% endblock %}
</div>
<!-- ./wrapper -->

<!-- REQUIRED SCRIPTS -->

<!-- jQuery -->
<script src="{% static 'adminLTE/plugins/jquery/jquery.min.js' %}"></script>
<!-- Bootstrap 4 -->
<script src="{% static 'adminLTE/plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<!-- AdminLTE App -->
<script src="{% static 'adminLTE/js/adminlte.min.js' %}"></script>
</body>
</html>

templates/footer.html
{% load static %}

{% block footer %}
    <!-- Main Footer -->
    <footer class="main-footer">
        <!-- To the right -->
        <div class="float-right d-none d-sm-inline">
            r+prof
        </div>
        <!-- Default to the left -->
        {% if user.is_authenticated %}
            <strong>Copyright &copy; 2021 <a href="{% url 'gestao_escolar:homepage_blank' %}">r+Prof</a>.</strong> All rights reserved.
        {% else %}
            <strong>Copyright &copy; 2021 <a href="{% url 'landing_page:landing_page' %}">r+Prof</a>.</strong> All rights reserved.
        {% endif %}
    </footer>
{% endblock %}

templates/sidebar.html
{% load static %}

{% block sidebar %}

    <!-- Main Sidebar Container -->
    <aside class="main-sidebar sidebar-dark-primary elevation-4">
        <!-- Brand Logo -->
        <a href="{% url 'gestao_escolar:school_year' %}" class="brand-link">
            <img src="{% static 'r+prof/img/rProf_Logo.png' %}" alt="r+Prof Logo"
                 class="brand-image img-circle elevation-3"
                 style="opacity: .8">
            <span class="brand-text font-weight-light">r+Prof</span>
        </a>

        <!-- Sidebar -->
        <div class="sidebar">
            <!-- Sidebar user panel (optional) -->
            <div class="user-panel mt-3 pb-3 mb-3 d-flex">
                <div class="image">
                    <img src="{{user.avatar.url}}" class="img-circle elevation-2"
                         alt="User Image">
                </div>
                <div class="info">
                    <a href="#" class="d-block">{{ user }}</a>
                </div>
            </div>

            <!-- Sidebar Menu -->
            <nav class="mt-2">
                <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu"
                    data-accordion="false">
                    <!-- Add icons to the links using the .nav-icon class
                         with font-awesome or any other icon font library -->

                    <!-- Separador Escola -->
                    <li class="nav-item has-treeview">
                        <a href="{% url 'gestao_escolar:school_list' %}" class="nav-link">
                            <i class="nav-icon fas fa-school"></i>
                            <p>
                                Escolas
                                {% if quantidade_escolas %}
                                    <span class="badge badge-info right"> {{ quantidade_escolas }} </span>
                                {% endif %}
                            </p>
                        </a>
                    </li>

                    <!-- separador anos letivos  -->
                    <li class="nav-item has-treeview">
                        <a href="#" class="nav-link active"> <!-- mudar a cor azul?? -->
                            <i class="nav-icon fas fa-suitcase"></i>
                            <p>
                                Anos Letivos
                                <i class="right fas fa-angle-left"></i>
                            </p>
                        </a>
                        <ul class="nav nav-treeview">
                            {% if anos_letivos_side_bar %}
                                {% for ano_letivo in anos_letivos_side_bar %}
                                    <li class="nav-item">
                                        <a href="{% url 'gestao_escolar:school_class_list' ano_letivo.slug %}" class="nav-link active">
                                            <i class="far fa-circle nav-icon"></i>
                                            <p>{{ ano_letivo.name }}</p>
                                        </a>
                                    </li>
                                {% endfor %}
                                <li class="nav-item">
                                    <a href="{% url 'gestao_escolar:school_year_list' %}" class="nav-link">
                                        <i class="far fa-circle nav-icon"></i>
                                        <p>Ver todos</p>
                                        <span class="badge badge-info right">{{ anos_letivos_count }}</span>
                                    </a>
                                </li>
                            {% endif %}
                            <li class="nav-item">
                                <a href="{% url 'gestao_escolar:school_year_add' %}" class="nav-link">
                                    <i class="far fa-circle nav-icon"></i>
                                    <p>Adicionar</p>
                                </a>
                            </li>
                        </ul>
                    </li>

                    {% if ano_letivo_corrente %}
                        <li class="nav-header">CONTEÚDO DE {{ ano_letivo_corrente }}</li>

                        <!-- Separador Turmas -->
                        <li class="nav-item has-treeview">
                            <a href="#" class="nav-link">
                                <i class="nav-icon fas fa-chalkboard-teacher"></i>
                                <p>
                                    Turmas
                                    <i class="right fas fa-angle-left"></i>
                                </p>
                            </a>
                            <ul class="nav nav-treeview">
                                <li class="nav-item">
                                    <a href="{% url 'gestao_escolar:school_class_list' ano_letivo_corrente.slug %}" class="nav-link">
                                        <i class="far fa-circle nav-icon"></i>
                                        <p>Ver todas</p>
                                        {% if quantidade_turmas %}
                                            <span class="badge badge-info right">{{ quantidade_turmas }}</span>
                                        {% endif %}
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a href="{% url 'gestao_escolar:school_class_add' ano_letivo_corrente.slug %}" class="nav-link">
                                        <i class="far fa-circle nav-icon"></i>
                                        <p>Adicionar</p>
                                    </a>
                                </li>
                            </ul>
                        </li>
                    {% endif %}
                    <li class="nav-item">
                        <a href="{% url 'contas:logout' %}" class="nav-link">
                            <i class="nav-icon fas fa-sign-out-alt"></i>
                            <p>
                                Sair
                            </p>
                        </a>
                    </li>
                </ul>
            </nav>
            <!-- /.sidebar-menu -->
        </div>
        <!-- /.sidebar -->
    </aside>

{% endblock %}