apps/gestao_escolar/urls.py
from apps.gestao_escolar import views
from django.urls import path

app_name = 'gestao_escolar'

urlpatterns = [

    path("", views.homepage, name="homepage_blank"),
    path("ano-letivo/lista/", views.school_year_list, name="school_year_list"),
    path("ano-letivo/criar/", views.school_year_add, name="school_year_add"),
    path("ano-letivo/<ano_letivo_slug>/alterar", views.school_year_change, name="school_year_change"),
    path("ano-letivo/<ano_letivo_slug>/remover", views.school_year_delete, name="school_year_delete"),

    path("ano-letivo/", views.homepage, name="school_year"),

    path("ano-letivo/<ano_letivo_slug>/turma/lista", views.homepage, name="school_class_list"),

    path("ano-letivo/<ano_letivo_slug>/turma/criar", views.school_class_add, name="school_class_add"),
    path("ano-letivo/<ano_letivo_slug>/turma/<turma_slug>", views.school_class_detail, name="school_class_detail"),
    path("ano-letivo/<ano_letivo_slug>/turma/<turma_slug>/alterar", views.school_class_change,
         name="school_class_change"),
    path("ano-letivo/<ano_letivo_slug>/turma/<turma_slug>/remover", views.school_class_delete,
         name="school_class_delete"),
    path("ano-letivo/<ano_letivo_slug>/turma/<turma_slug>/aluno/criar", views.student_add,
         name="student_add"),
    path("ano-letivo/<ano_letivo_slug>/turma/<turma_slug>/aluno/criar_alunos", views.student_add_multiple,
         name="student_add_multiple"),

    path("ano-letivo/<ano_letivo_slug>/turma/<turma_slug>/aluno/<aluno_slug>", views.student_detail,
         name="student_detail"),
    path("ano-letivo/<ano_letivo_slug>/turma/<turma_slug>/aluno/<aluno_slug>/alterar", views.student_change,
         name="student_change"),
    path("ano-letivo/<ano_letivo_slug>/turma/<turma_slug>/aluno/<aluno_slug>/alterar_foto", views.student_foto_change,
         name="student_foto_change"),
    path("ano-letivo/<ano_letivo_slug>/turma/<turma_slug>/aluno/<aluno_slug>/remover", views.student_delete,
         name="student_delete"),

    path("escola/lista", views.school_list, name="school_list"),
    path("escola/criar", views.school_add, name="school_add"),
    path("escola/<escola_slug>/alterar", views.school_change, name="school_change"),
    path("escola/<escola_slug>/remover", views.school_delete, name="school_delete"),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.landing_page.urls')),
    path('contas/', include('apps.contas.urls')),
    path('gestao_escolar/', include('apps.gestao_escolar.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/gestao_escolar/forms.py
from django.core.exceptions import ValidationError
from django.forms import ModelForm
from django.forms.models import modelformset_factory

from .models import Escola, AnoLetivo, Turma, Aluno


# https://www.geeksforgeeks.org/django-modelform-create-form-from-models/
# https://developer.mozilla.org/en-US/docs/Learn/Server-side/Django/Forms


class EscolaForm(ModelForm):
    class Meta:
        model = Escola
        exclude = ['user', 'slug', 'created', 'modified', ]


def date_validation(start_date, end_date):
    # validação dos campos 'data inicial' e 'data final'
    if start_date and end_date:
        if end_date < start_date:
            raise ValidationError(
                'A data final não pode ocorrer antes da data inicial!'
            )


class AnoLetivoChangeForm(ModelForm):
    # https: // stackoverflow.com / questions / 2141030 / djangos - modelform - unique - together - validation
    class Meta:
        model = AnoLetivo
        fields = [
            'name', 'start_date', 'end_date',
        ]
        help_texts = {
            'name': ' formato: aaaa/aaaa',
        }

    def clean(self):
        cleaned_data = self.cleaned_data
        start_date = cleaned_data['start_date']
        end_date = cleaned_data['end_date']

        if AnoLetivo.objects.exclude(pk=self.instance.pk).filter(
                name=cleaned_data['name'], user=self.instance.user).exists():
            raise ValidationError('Já tem um ano letivo com esta designação!')

        # validação dos campos 'data inicial' e 'data final'
        date_validation(start_date, end_date)

        # retorna sempre 'cleaned_data'
        return cleaned_data


class AnoLetivoAddForm(ModelForm):
    class Meta:
        model = AnoLetivo
        fields = [
            'name', 'start_date', 'end_date',
        ]
        help_texts = {
            'name': ' formato: aaaa/aaaa',
        }

    def clean(self):
        cleaned_data = self.cleaned_data
        start_date = cleaned_data['start_date']
        end_date = cleaned_data['end_date']

        try:
            AnoLetivo.objects.get(name=cleaned_data['name'], user=self.instance.user)
        except AnoLetivo.DoesNotExist:
            # Este utilizador não tem nenhum objeto com o mesmo nome.
            # Então tudo ok. não existe erro de validação do 'unique_together'
            pass
        else:
            raise ValidationError('Já tem um ano letivo com esta designação!')

        # validação dos campos 'data inicial' e 'data final'
        date_validation(start_date, end_date)

        # retorna sempre 'cleaned_data'
        return cleaned_data

    # # outra forma de verificar o unique_together


# https://stackoverflow.com/questions/32260785/django-validating-unique-together-constraints-in-a-modelform-with-excluded-fiel


class TurmaForm(ModelForm):
    class Meta:
        model = Turma
        fields = [
            'escola', 'name', 'grade', 'subject',
            'class_type', 'dt_name', 'dt_phone', 'dt_email'
        ]


class AlunoChangeForm(ModelForm):
    class Meta:
        model = Aluno
        fields = [
            'name', 'birth_date', 'sex', 'class_number', 'class_shift',
            'email', 'phone', 'address', 'tutor_name', 'tutor_email',
            'tutor_phone', 'observations',
        ]


class AlunoFotoChangeForm(ModelForm):
    class Meta:
        model = Aluno
        fields = ['foto', ]


class AlunoAddForm(ModelForm):
    class Meta:
        model = Aluno
        fields = ['name', 'class_number']


AlunoAddMultipleFormSet = modelformset_factory(
    Aluno, fields=(
        'name',
    ), extra=1,
)

apps/gestao_escolar/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.core.exceptions import ObjectDoesNotExist
from django.contrib import messages

from apps.gestao_escolar.models import AnoLetivo, Turma, Aluno, Escola
from .forms import EscolaForm, AnoLetivoAddForm, AnoLetivoChangeForm, TurmaForm, AlunoChangeForm, AlunoFotoChangeForm, \
    AlunoAddForm, AlunoAddMultipleFormSet


# importante ver isto
# unique slug
# https://stackoverflow.com/questions/21023813/django-saving-unique-entries-by-automatically-appending-a-counter-to-the-title

# Create your views here.
@login_required
def homepage(request, ano_letivo_slug=None):
    """
    Apresenta a página inicial do utilizador com login efetuado.
    -> Se forem passados dois argumentos (user e ano_letivo) apresenta as turmas do ano letivo selecionado.
    -> Se for passado um argumento (user) apresenta as turmas do último ano letivo modificado.
    -> Se for passado um argumento (user) e não existirem anos letivos (1ª utilização da plataforma ou livro em branco)
       apresenta html com indicações para o início do registo de turmas.
    """

    if ano_letivo_slug is not None:
        """ 
        apresenta as turmas do ano letivo selecionado no argumento 'ano_letivo'
        quando o utilizador pede para ver um ano letivo especifico
        passa esse argumento no 'slug' 
        """
        ano_letivo_corrente = AnoLetivo.objects.get(
            user=request.user,
            slug=ano_letivo_slug,
        )
    else:
        try:
            """
            Neste caso não há 'slug' passado no argumento da função.
            Verifica se o utilizador têm anos letivos registados na plataforma e 
            devolve o último que foi alterado. 
            """
            ano_letivo_corrente = AnoLetivo.objects.filter(user=request.user).latest('modified')

        except ObjectDoesNotExist:
            """
            Senão, recupera do erro anterior... é a primeira utilização do programa, não existem
            registos de Anos letivos. Apresenta HTML com indicações para a criação desses objetos.
            """
            template_name = 'gestao_escolar/homepage_first_use.html'
            return render(request, template_name)

        """
        se o utilizador registos de anos letivos, atualiza regista o ano letivo da ultima turma modificada e
        chama novamente a função com os argumentos atualizados
        """
        return redirect(
            'gestao_escolar:school_class_list',
            ano_letivo_slug=ano_letivo_corrente.slug
        )

    template_name = 'gestao_escolar/homepage.html'

    quantidade_escolas = Escola.objects.filter(
        user=request.user,
    ).count()

    anos_letivos_barra_lateral = AnoLetivo.objects.filter(
        user=request.user,
    ).order_by('-modified')[:3]
    quantidade_anos_letivos = AnoLetivo.objects.filter(
        user=request.user,
    ).count()

    try:
        turmas = Turma.objects.filter(
            user=request.user,
            ano_letivo=ano_letivo_corrente
        )
        quantidade_turmas = turmas.count()
    except ObjectDoesNotExist:
        turmas = None
        quantidade_turmas = 0

    context = {
        'ano_letivo_corrente': ano_letivo_corrente,
        'anos_letivos_side_bar': anos_letivos_barra_lateral,
        'quantidade_escolas': quantidade_escolas,
        'anos_letivos_count': quantidade_anos_letivos,
        'turmas': turmas,
        'quantidade_turmas': quantidade_turmas,
        # 'dicionario_turmas': dicionario_turmas,
        # 'disciplinasTurma': disciplinasTurma,
        # 'dicionario_disciplinas_turmas': dicionario_disciplinas_turmas,
        # 'alunos': alunos,
        # 'total_alunos': total_alunos,
        # 'alunOs': alunOs,
        # 'alunAs': alunAs,
    }

    return render(request, template_name, context)


# *** Escola_views ***********************************************************************

def side_bar_func(request, context):
    quantidade_escolas = Escola.objects.filter(
        user=request.user,
    ).count()

    anos_letivos_barra_lateral = AnoLetivo.objects.filter(
        user=request.user,
    ).order_by('-modified')[:3]
    quantidade_anos_letivos = AnoLetivo.objects.filter(
        user=request.user,
    ).count()

    context.update({
        'anos_letivos_side_bar': anos_letivos_barra_lateral,
        'quantidade_escolas': quantidade_escolas,
        'anos_letivos_count': quantidade_anos_letivos,
    })

    return context


@login_required
def school_list(request):
    """
    Apresenta a lista de todas as escolas do utilizador corrente.
    # link => side_bar -> botão Escolas
    # url -> path("escola/lista", views.school_list, name="school_list"),
    """

    template_name = 'gestao_escolar/school_list.html'
    context = {}

    try:
        escola_list = Escola.objects.all().filter(user=request.user)
        sl = {'school_list': escola_list}
        context.update(sl)

    except ObjectDoesNotExist:
        msg = {'message': 'Ainda não tem escolas registadas!!'}
        context.update(msg)

    context = side_bar_func(request, context)

    return render(request, template_name, context)


@login_required
def school_add(request):
    """
        Apresenta formulario para adição de escola.
        # link => na lista de escolas -> link para adicionar
        # path("escola/criar", views.school_add, name="school_add"),
    """

    form = EscolaForm(request.POST or None)
    if form.is_valid():
        school = form.save(commit=False)
        school.user_id = request.user.id
        school.save()
        messages.success(request, f"'Escola '{school.name}' adicionada com sucesso ")
        return redirect('gestao_escolar:school_list')

    template_name = 'gestao_escolar/school_add.html'
    context = {'form': form}

    context = side_bar_func(request, context)

    return render(request, template_name, context)


@login_required
def school_change(request, escola_slug):
    """
        Apresenta os dados de uma escola e permite que o utilizador os altere.
        # link => cartão de cada escola no -> more info
        # path("escola/<escola_slug>/remover", views.school_delete, name="school_delete"),,
    """

    school = get_object_or_404(Escola, slug=escola_slug)
    form = EscolaForm(request.POST or None, instance=school)
    if form.is_valid():
        form.save()
        return redirect('gestao_escolar:school_list')

    template_name = 'gestao_escolar/school_change.html'
    context = {'form': form,
               'school': school
               }

    context = side_bar_func(request, context)

    return render(request, template_name, context)


# https://stackoverflow.com/questions/46003056/how-to-make-delete-button-in-django/46006826
@login_required
def school_delete(request, escola_slug):
    """
    delete a school object
    link - página com um botão a dizer " pretende mesmo remover esta escola?"
    path("escola/<escola_slug>/remover", views.school_delete, name="school_delete"),
    """

    school = get_object_or_404(Escola, slug=escola_slug)

    if request.method == 'POST':
        messages.success(request, f"'Escola '{school.name}' removida com sucesso ")
        school.delete()
        return redirect('gestao_escolar:school_list')

    template_name = 'gestao_escolar/school_delete.html'
    context = {'school': school}

    context = side_bar_func(request, context)

    return render(request, template_name, context)


# *** Ano_Letivo_views ***********************************************************************

@login_required
def school_year_list(request):
    """
    Apresenta a lista de todos os anos letivos do utilizador corrente.
    # link => side_bar -> botão Anos Letivos -> Ver todos.
    # path("ano-letivo/lista/", views.school_year_list, name="school_year_list"),
    """
    template_name = 'gestao_escolar/school_year_list.html'
    context = {}

    try:
        ano_letivo_list = AnoLetivo.objects.all().filter(user=request.user)
        syl = {'school_year_list': ano_letivo_list}
        context.update(syl)

    except ObjectDoesNotExist:
        msg = {'message': 'Ainda não tem Anos Letivos registados!!'}
        context.update(msg)

    context = side_bar_func(request, context)

    return render(request, template_name, context)


@login_required
def school_year_add(request):
    """
        Apresenta formulário para adição de um ano letivo.
        # link => barra lateral -> link para adicionar
        # path("ano-letivo/criar/", views.school_year_add, name="school_year_add"),
    """
    ano_letivo = AnoLetivo()
    ano_letivo.user = request.user
    form = AnoLetivoAddForm(request.POST or None, instance=ano_letivo)
    if request.method == 'POST':
        if form.is_valid():
            ano_letivo = form.save(commit=False)
            ano_letivo.user_id = request.user.id
            ano_letivo.save()
            messages.success(request, f"'Ano Letivo '{ano_letivo.name}' adicionado com sucesso ")
            return redirect('gestao_escolar:school_year_list')
        else:
            messages.error(request, "Corrija os erros abaixo indicados!")

    template_name = 'gestao_escolar/school_year_add.html'
    context = {'form': form}

    context = side_bar_func(request, context)

    return render(request, template_name, context)


@login_required
def school_year_change(request, ano_letivo_slug):
    """
        Apresenta os dados de um ano letivo e permite que o utilizador os altere.
        # link => cartão de cada ano letivo no -> more info
        # path("ano-letivo/<ano_letivo_slug>/alterar", views.school_year_change, name="school_year_change"),
    """

    ano_letivo = get_object_or_404(AnoLetivo, slug=ano_letivo_slug)
    form = AnoLetivoChangeForm(request.POST or None, instance=ano_letivo)
    if request.method == 'POST':
        if form.is_valid():
            form.save()

templates/gestao_escolar/homepage.html
{% extends 'base.html' %}
{% block content %}
    <!-- Content Header (Page header) -->
    <section class="content-header" style="padding-bottom: 0px;">
        <div class="container-fluid">
            <h4>&nbsp; Ano letivo&nbsp{{ ano_letivo_corrente.name }}</h4>
        </div><!-- /.container-fluid -->
    </section>
    <section class="content">
        <div class="container-fluid">
            <div class="col-sm-6">
                {% if not turmas %}
                    <br>
                    <div class="callout callout-info">
                        <h5>Ainda não tem turmas registadas! Adicionar turma
                            <a href="{% url 'gestao_escolar:school_class_add' ano_letivo_corrente.slug %}"
                               class="small-box-footer">

                                <i class="fas fa-plus-circle"></i>
                            </a>
                        </h5>
                    </div>
                {% else %}
                    <div class="row">
                        <h3 class="mb-2 mt-4">&nbsp;Turmas
                            <a href="{% url 'gestao_escolar:school_class_add' ano_letivo_corrente.slug %}"
                               class="small-box-footer">
                                <i class="fas fa-plus-circle"></i>
                            </a></h3>
                        </h3>
                    </div>
                    </div>

                    <div class="row">
                        {% for turma in turmas %}
                            <div class="col-lg-3 col-6">
                                <!-- small card -->
                                <div class="small-box bg-gradient-orange">
                                    <div class="inner" style="color: whitesmoke">
                                        <a href="{% url 'gestao_escolar:school_class_detail' ano_letivo_corrente.slug turma.slug %}"
                                           class="small-box-footer" style="color: whitesmoke">
                                            <h5 class="text-truncate">{{ turma.name }} {% if turma.subject %} -
                                                {{ turma.subject }} {% endif %}
                                            </h5>
                                        </a>
                                        <small>
                                            {% if  turma.escola %}
                                                {{ turma.escola }}
                                            {% endif %}
                                        </small>
                                        <br>
                                        <small>
                                            Diretor de Turma: {{ turma.dt_name }}
                                        </small>
                                        <br>
                                    </div>
                                    <div class="icon">
                                        <i class="fas fa-chalkboard-teacher"></i>
                                    </div>
                                    <a href="{{ turma.get_absolute_url }}" class="small-box-footer">
                                        <i class="fas fa-edit"></i>
                                    </a>
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                {% endif %}
        </div><!-- /.container-fluid -->
    </section>
    <!-- /.content -->
{% endblock %}

templates/gestao_escolar/homepage_first_use.html
{% extends 'base.html' %}
{% block content %}
    <br>
    <section class="content">
        <div class="callout callout-info">
            <h5>É a sua primeira utilização, seja bem vindo {{ user }}!</h5>
            Para começar deve criar um ano letivo.
            <div class="container">
                <div class="row">
                    <div class="col text-center">
                        <a href="{% url 'gestao_escolar:school_year_add' %}" class="nav-link">
                            <button type="button" class="btn btn-primary btn-info">Adicionar ano letivo</button>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- /.content -->
{% endblock %}

templates/gestao_escolar/school_class_detail.html
{% extends 'base.html' %}
{% block content %}

    <!-- Content Header (Page header) -->
    <section class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h4> Ano letivo&nbsp{{ school_year.name }}</h4>
                    <h3>Turma&nbsp{{ school_class.name }}</h3>
                </div>
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item">
                            <a href="{% url 'gestao_escolar:school_year' %}">
                                Voltar &nbsp
                            </a>
                        </li>
                    </ol>
                </div>
            </div>
        </div><!-- /.container-fluid -->
    </section>

    <!-- Main content -->
    <section class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-12">
                    <div class="card collapsed-card">
                        <div class="card-header">
                            <h3 class="card-title">Lista de alunos da turma</h3>

                            {#                            <div class="card-tools">#}
                            {#                                <div class="input-group input-group-sm">#}
                            {#                                    <div class="input-group-append">#}
                            {##}
                            {#                                        <a href="{% url 'student_add_multiple' school_year.slug school_class.slug %}">#}
                            {#                                            <span class="fas fa-user-plus" style="color: blue">&nbsp;</span>#}
                            {#                                        </a>#}
                            {#                                        Adicionar Alunos&nbsp;#}
                            {#                                    </div>#}
                            {#                                </div>#}
                            {#                            </div>#}

                            <div class="card-tools">
                                {% if total_students == 1 %}
                                    <span class="badge badge-info">{{ total_students }} aluno na turma</span>
                                {% else %}
                                    <span class="badge badge-info">{{ total_students }} alunos na turma</span>
                                {% endif %}
                                <button type="button" class="btn btn-tool" data-card-widget="collapse"><i
                                        class="fas fa-plus"></i>
                                </button>
                            </div>
                        </div>
                        <!-- /.card-header -->
                        <div class="card-body table-responsive p-0" style="height: 300px;">
                            <table class="table table-hover text-nowrap">
                                <thead>
                                <tr>
                                    <th>N.º aluno</th>
                                    <th>Nome</th>
                                    <th>Idade</th>
                                    <th>Sexo</th>
                                    <th>Turno</th>
                                    <th>Obs.</th>
                                    <th></th>
                                </tr>
                                </thead>
                                <!-- /.thead -->
                                <tbody>
                                {% for student in students %}
                                    <tr>
                                        <td>
                                            {{ student.class_number }}
                                        </td>
                                        <td>
                                            <div class="input-group-append">
                                                <a href="{% url 'gestao_escolar:student_detail' school_year.slug school_class.slug student.slug %}">
                                                    {{ student.name }}
                                                </a>

                                            </div>
                                        </td>
                                        <td>
                                            {% if student.get_age %}
                                                {{ student.get_age }}
                                            {% else %}
                                                ---
                                            {% endif %}
                                        </td>
                                        <td>
                                            <span class="tag tag-success">
                                            {% if student.sex %}
                                                {{ student.sex }}
                                            {% else %}
                                                ---
                                            {% endif %}
                                            </span>
                                        </td>
                                        <td>
                                            {% if student.class_shift %}
                                                {{ student.class_shift }}
                                            {% else %}
                                                ---
                                            {% endif %}
                                        </td>
                                        <td>
                                            {% if student.observations %}
                                                {{ student.observations }}
                                            {% else %}
                                                ---
                                            {% endif %}
                                        </td>
                                        <td>
                                            <div class="input-group-append">
                                                <a href="{% url 'gestao_escolar:student_change' school_year.slug school_class.slug student.slug %}">
                                                    <span class="fas fa-edit" style="color: blue"></span>
                                                </a>
                                                &nbsp; &nbsp; &nbsp;
                                                <a href="{% url 'gestao_escolar:student_delete' school_year.slug school_class.slug student.slug %}">
                                                    <span class="far fa-trash-alt" style="color: red"></span>
                                                </a>
                                            </div>
                                        </td>
                                    </tr>
                                {% endfor %}
                                </tbody>
                                <!-- /.tbody -->
                            </table>
                            <!-- /.table -->
                        </div>
                        <!-- /.card-body -->
                        <div class="card-footer text-center">
                            <a href="{% url 'gestao_escolar:student_add_multiple' school_year.slug school_class.slug %}">
                                <span class="fas fa-user-plus" style="color: blue">&nbsp;</span>
                            </a>
                            Adicionar Alunos
                        </div>
                        <!-- /.card-footer -->
                    </div>
                    <!-- /.card -->
                    <div class="card collapsed-card">
                        <div class="card-header">
                            <h3 class="card-title">Fotos</h3>
                            <div class="card-tools">
                                {% if total_students == 1 %}
                                    <span class="badge badge-info">{{ total_students }} aluno na turma</span>
                                {% else %}
                                    <span class="badge badge-info">{{ total_students }} alunos na turma</span>
                                {% endif %}
                                <button type="button" class="btn btn-tool" data-card-widget="collapse"><i
                                        class="fas fa-plus"></i>
                                </button>
                            </div>
                        </div>
                        <!-- /.card-header -->
                        <div class="card-body p-0">
                            <ul class="users-list clearfix ">
                                {% for student in students %}
                                    <li>
                                        <a class="users-list-name"
                                           href="{% url 'gestao_escolar:student_detail' school_year.slug school_class.slug student.slug %}">
                                            <img src="{{ student.foto.url }}" style="width: 125px; height: 125px"
                                                 alt="Student foto"> <br>
                                            {{ student.class_number }} - {{ student.name }}
                                        </a>
                                    </li>
                                {% endfor %}
                            </ul>
                            <!-- /.users-list -->
                        </div>
                        <!-- /.card-body -->
                        <div class="card-footer text-center">
                            <a href="{% url 'gestao_escolar:school_year' %}">Voltar</a>
                        </div>
                        <!-- /.card-footer -->
                    </div>
                    <!-- /.card -->
                </div>
                <!-- /.col -->
            </div>
            <!-- /.row -->
        </div>
        <!-- /.container-fluid -->
    </section>
    <!-- /.content -->
{% endblock %}